import argparse
import json
import numpy as np
import matplotlib.pyplot as plt
import os

def load_fu(path):
    with open(path, 'r') as f:
        data = json.load(f)
    return data

def extract_weights(data):
    weights = []
    # Extract w1
    if 'w1' in data:
        w_obj = data['w1']
        dim = w_obj['dim']
        # ndarray serialized data is flattened. dim is [rows, cols]
        w_arr = np.array(w_obj['data']).reshape(dim)
        weights.append(('Layer 1 Weights (Input -> Hidden)', w_arr))
    
    # Extract w2
    if 'w2' in data:
        w_obj = data['w2']
        dim = w_obj['dim']
        w_arr = np.array(w_obj['data']).reshape(dim)
        weights.append(('Layer 2 Weights (Hidden -> Output)', w_arr))
        
    return weights

def plot_weights(weights, fu_name, filename, output_path):
    num_plots = len(weights)
    if num_plots == 0:
        print("No weights found to plot.")
        return

    fig, axes = plt.subplots(1, num_plots, figsize=(6 * num_plots, 6))
    if num_plots == 1:
        axes = [axes]
    
    for ax, (title, w) in zip(axes, weights):
        # Determine color limits
        vmax = np.max(np.abs(w))
        im = ax.imshow(w, cmap='coolwarm', vmin=-vmax, vmax=vmax, aspect='auto')
        ax.set_title(title)
        ax.set_xlabel('Input Index')
        ax.set_ylabel('Neuron Index')
        fig.colorbar(im, ax=ax, orientation='horizontal', label='Weight Value')

    # Add Caption
    caption = f"Functional Unit: {fu_name}\nSource File: {filename}\nGenerated by Neuro-Symbolic Emulator"
    fig.text(0.5, 0.01, caption, ha='center', fontsize=10, style='italic')
    
    plt.tight_layout(rect=[0, 0.05, 1, 0.95]) # Make space for caption
    plt.savefig(output_path)
    print(f"Saved visualization to {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Visualize Neural Functional Unit Weights")
    parser.add_argument("file", help="Path to the FU JSON file")
    parser.add_argument("--output", "-o", help="Output image file path (default: <fu_name>.png)")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.file):
        print(f"Error: File {args.file} not found.")
        return

    data = load_fu(args.file)
    weights = extract_weights(data)
    
    filename = os.path.basename(args.file)
    fu_name = filename.replace('.json', '')
    
    output = args.output if args.output else f"{fu_name}_heatmap.png"
    
    plot_weights(weights, fu_name, filename, output)

if __name__ == "__main__":
    main()
